version: '3.8'

services:
  mcp-server:
    build: .
    container_name: mcp-server
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped 