name: TypeScript Validaci贸n

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  typecheck:
    name: Verificar tipos TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Verificar tipos (TypeScript)
        run: npm run typecheck

  eslint:
    name: Lint con ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar ESLint
        run: npm run lint

  tests:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests
        run: npm test 